version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/actors.log
    env_file:
      - .env.local
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped